const employees = [
  {
    fullName: "Nguyen Van An",
    phoneNumber: "0987654321",
    candidateSource: "Facebook",
    email: "an.nguyen@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "Frontend Developer",
    jobPosting: "ReactJS Developer",
    recruitmentStage: "CV Screening",
    evaluation: "Potential",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Cau Giay",
  },
  {
    fullName: "Tran Thi Bich",
    phoneNumber: "0978123456",
    candidateSource: "LinkedIn",
    email: "bich.tran@gmail.com",
    recruitmentCampaign: "Intern Hiring 2026",
    position: "Backend Intern",
    jobPosting: "Java Spring Boot",
    recruitmentStage: "HR Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Dong Da",
  },
  {
    fullName: "Le Minh Cuong",
    phoneNumber: "0912345678",
    candidateSource: "TopCV",
    email: "cuong.le@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "Fullstack Developer",
    jobPosting: "NodeJS + React",
    recruitmentStage: "Technical Interview",
    evaluation: "Average",
    country: "Vietnam",
    province: "Da Nang",
    ward: "Hai Chau",
  },
  {
    fullName: "Pham Thu Dung",
    phoneNumber: "0909123456",
    candidateSource: "Website",
    email: "dung.pham@gmail.com",
    recruitmentCampaign: "Marketing Hiring",
    position: "Digital Marketing",
    jobPosting: "Marketing Executive",
    recruitmentStage: "CV Screening",
    evaluation: "Average",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Thanh Xuan",
  },
  {
    fullName: "Do Hoang Nam",
    phoneNumber: "0933456789",
    candidateSource: "Referral",
    email: "nam.do@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "Backend Developer",
    jobPosting: "Java Developer",
    recruitmentStage: "Offer",
    evaluation: "Excellent",
    country: "Vietnam",
    province: "Hai Phong",
    ward: "Le Chan",
  },
  {
    fullName: "Nguyen Thi Hoa",
    phoneNumber: "0966111222",
    candidateSource: "Facebook",
    email: "hoa.nguyen@gmail.com",
    recruitmentCampaign: "Intern Hiring 2026",
    position: "Frontend Intern",
    jobPosting: "React Intern",
    recruitmentStage: "HR Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Ba Dinh",
  },
  {
    fullName: "Bui Van Khanh",
    phoneNumber: "0944556677",
    candidateSource: "LinkedIn",
    email: "khanh.bui@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "DevOps Engineer",
    jobPosting: "AWS DevOps",
    recruitmentStage: "Technical Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ho Chi Minh",
    ward: "District 7",
  },
  {
    fullName: "Phan Ngoc Lan",
    phoneNumber: "0922333444",
    candidateSource: "TopCV",
    email: "lan.phan@gmail.com",
    recruitmentCampaign: "HR Hiring",
    position: "HR Executive",
    jobPosting: "HR Generalist",
    recruitmentStage: "HR Interview",
    evaluation: "Average",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Hoan Kiem",
  },
  {
    fullName: "Vu Duc Thanh",
    phoneNumber: "0911222333",
    candidateSource: "Website",
    email: "thanh.vu@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "Backend Developer",
    jobPosting: "Spring Boot Developer",
    recruitmentStage: "CV Screening",
    evaluation: "Potential",
    country: "Vietnam",
    province: "Da Nang",
    ward: "Son Tra",
  },
  {
    fullName: "Trinh Mai Anh",
    phoneNumber: "0988111222",
    candidateSource: "Facebook",
    email: "anh.trinh@gmail.com",
    recruitmentCampaign: "Marketing Hiring",
    position: "Content Marketing",
    jobPosting: "Content Creator",
    recruitmentStage: "Final Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Tay Ho",
  },
  {
    fullName: "Dang Tuan Kiet",
    phoneNumber: "0977111222",
    candidateSource: "LinkedIn",
    email: "kiet.dang@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "Frontend Developer",
    jobPosting: "VueJS Developer",
    recruitmentStage: "Technical Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ho Chi Minh",
    ward: "District 3",
  },
  {
    fullName: "Hoang Minh Duc",
    phoneNumber: "0967222333",
    candidateSource: "TopCV",
    email: "duc.hoang@gmail.com",
    recruitmentCampaign: "Intern Hiring 2026",
    position: "Backend Intern",
    jobPosting: "NodeJS Intern",
    recruitmentStage: "HR Interview",
    evaluation: "Potential",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Nam Tu Liem",
  },
  {
    fullName: "Nguyen Quoc Huy",
    phoneNumber: "0955333444",
    candidateSource: "Facebook",
    email: "huy.nguyen@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "Fullstack Developer",
    jobPosting: "React + Spring Boot",
    recruitmentStage: "Technical Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Da Nang",
    ward: "Thanh Khe",
  },
  {
    fullName: "Le Thi Thao",
    phoneNumber: "0946444555",
    candidateSource: "Website",
    email: "thao.le@gmail.com",
    recruitmentCampaign: "Marketing Hiring",
    position: "SEO Specialist",
    jobPosting: "SEO Executive",
    recruitmentStage: "CV Screening",
    evaluation: "Average",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Long Bien",
  },
   {
    fullName: "Nguyen Van Minh",
    phoneNumber: "0912345678",
    candidateSource: "Facebook",
    email: "minh.nguyen@gmail.com",
    recruitmentCampaign: "Tech Hiring",
    position: "Frontend Developer",
    jobPosting: "React Developer",
    recruitmentStage: "Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Cau Giay"
  },
  {
    fullName: "Tran Thi Hoa",
    phoneNumber: "0988777666",
    candidateSource: "LinkedIn",
    email: "hoa.tran@gmail.com",
    recruitmentCampaign: "Marketing Hiring",
    position: "Content Writer",
    jobPosting: "Content Marketing",
    recruitmentStage: "CV Screening",
    evaluation: "Average",
    country: "Vietnam",
    province: "Ho Chi Minh",
    ward: "District 1"
  },
  {
    fullName: "Pham Duc Anh",
    phoneNumber: "0977555444",
    candidateSource: "Website",
    email: "anh.pham@gmail.com",
    recruitmentCampaign: "Tech Hiring",
    position: "Backend Developer",
    jobPosting: "Java Developer",
    recruitmentStage: "Technical Test",
    evaluation: "Good",
    country: "Vietnam",
    province: "Da Nang",
    ward: "Hai Chau"
  },
  {
    fullName: "Le Thi Mai",
    phoneNumber: "0933666777",
    candidateSource: "Referral",
    email: "mai.le@gmail.com",
    recruitmentCampaign: "HR Hiring",
    position: "HR Executive",
    jobPosting: "HR Specialist",
    recruitmentStage: "Interview",
    evaluation: "Excellent",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Dong Da"
  },
  {
    fullName: "Nguyen Hoang Long",
    phoneNumber: "0911222333",
    candidateSource: "Facebook",
    email: "long.nguyen@gmail.com",
    recruitmentCampaign: "Tech Hiring",
    position: "Fullstack Developer",
    jobPosting: "NodeJS Developer",
    recruitmentStage: "Offer",
    evaluation: "Excellent",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Thanh Xuan"
  },
  {
    fullName: "Do Thi Lan",
    phoneNumber: "0966555444",
    candidateSource: "Website",
    email: "lan.do@gmail.com",
    recruitmentCampaign: "Marketing Hiring",
    position: "Digital Marketing",
    jobPosting: "Ads Specialist",
    recruitmentStage: "Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Hai Phong",
    ward: "Le Chan"
  },
  {
    fullName: "Bui Quang Huy",
    phoneNumber: "0944333222",
    candidateSource: "LinkedIn",
    email: "huy.bui@gmail.com",
    recruitmentCampaign: "Tech Hiring",
    position: "DevOps Engineer",
    jobPosting: "DevOps",
    recruitmentStage: "Technical Test",
    evaluation: "Average",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Nam Tu Liem"
  },
  {
    fullName: "Vu Thi Huong",
    phoneNumber: "0922111444",
    candidateSource: "Referral",
    email: "huong.vu@gmail.com",
    recruitmentCampaign: "Marketing Hiring",
    position: "Social Media Executive",
    jobPosting: "Social Media",
    recruitmentStage: "CV Screening",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Hoang Mai"
  },
  {
    fullName: "Dang Van Tuan",
    phoneNumber: "0933111222",
    candidateSource: "Facebook",
    email: "tuan.dang@gmail.com",
    recruitmentCampaign: "Tech Hiring",
    position: "QA Engineer",
    jobPosting: "Manual Tester",
    recruitmentStage: "Interview",
    evaluation: "Average",
    country: "Vietnam",
    province: "Bac Ninh",
    ward: "Tu Son"
  },
  {
    fullName: "Hoang Thi Yen",
    phoneNumber: "0911888999",
    candidateSource: "Website",
    email: "yen.hoang@gmail.com",
    recruitmentCampaign: "Sales Hiring",
    position: "Sales Executive",
    jobPosting: "Sales Representative",
    recruitmentStage: "Offer",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Ha Dong"
  },

  {
    fullName: "Nguyen Van Khoa",
    phoneNumber: "0977111222",
    candidateSource: "LinkedIn",
    email: "khoa.nguyen@gmail.com",
    recruitmentCampaign: "Tech Hiring",
    position: "Backend Developer",
    jobPosting: "Spring Boot Developer",
    recruitmentStage: "Technical Test",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Ba Dinh"
  },
  {
    fullName: "Tran Minh Duc",
    phoneNumber: "0966888222",
    candidateSource: "Website",
    email: "duc.tran@gmail.com",
    recruitmentCampaign: "Tech Hiring",
    position: "Frontend Developer",
    jobPosting: "VueJS Developer",
    recruitmentStage: "Interview",
    evaluation: "Average",
    country: "Vietnam",
    province: "Da Nang",
    ward: "Thanh Khe"
  },
  {
    fullName: "Le Thanh Tung",
    phoneNumber: "0955777888",
    candidateSource: "Referral",
    email: "tung.le@gmail.com",
    recruitmentCampaign: "Tech Hiring",
    position: "Mobile Developer",
    jobPosting: "Flutter Developer",
    recruitmentStage: "CV Screening",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Dong Anh"
  },
  {
    fullName: "Pham Thi Hang",
    phoneNumber: "0944999111",
    candidateSource: "Facebook",
    email: "hang.pham@gmail.com",
    recruitmentCampaign: "Marketing Hiring",
    position: "Content Creator",
    jobPosting: "TikTok Content",
    recruitmentStage: "Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ho Chi Minh",
    ward: "District 7"
  },
  {
    fullName: "Nguyen Quoc Bao",
    phoneNumber: "0933777444",
    candidateSource: "Website",
    email: "bao.nguyen@gmail.com",
    recruitmentCampaign: "Sales Hiring",
    position: "Business Development",
    jobPosting: "BD Executive",
    recruitmentStage: "Offer",
    evaluation: "Excellent",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Tay Ho"
  },
  {
    fullName: "Vu Duc Nam",
    phoneNumber: "0911222999",
    candidateSource: "LinkedIn",
    email: "nam.vu@gmail.com",
    recruitmentCampaign: "Tech Hiring",
    position: "System Engineer",
    jobPosting: "System Admin",
    recruitmentStage: "Technical Test",
    evaluation: "Average",
    country: "Vietnam",
    province: "Hai Phong",
    ward: "Ngo Quyen"
  },
  {
    fullName: "Doan Thi Linh",
    phoneNumber: "0988111333",
    candidateSource: "Referral",
    email: "linh.doan@gmail.com",
    recruitmentCampaign: "HR Hiring",
    position: "Recruiter",
    jobPosting: "HR Recruiter",
    recruitmentStage: "Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Thanh Xuan"
  },
  {
    fullName: "Hoang Van Phuc",
    phoneNumber: "0977666111",
    candidateSource: "Facebook",
    email: "phuc.hoang@gmail.com",
    recruitmentCampaign: "Tech Hiring",
    position: "Data Analyst",
    jobPosting: "Data Analyst",
    recruitmentStage: "CV Screening",
    evaluation: "Average",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Cau Giay"
  },
  {
    fullName: "Tran Thi Bich",
    phoneNumber: "0966333444",
    candidateSource: "Website",
    email: "bich.tran@gmail.com",
    recruitmentCampaign: "Marketing Hiring",
    position: "SEO Specialist",
    jobPosting: "SEO Executive",
    recruitmentStage: "Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Da Nang",
    ward: "Lien Chieu"
  },
  {
    fullName: "Nguyen Thanh Hai",
    phoneNumber: "0955444333",
    candidateSource: "LinkedIn",
    email: "hai.nguyen@gmail.com",
    recruitmentCampaign: "Tech Hiring",
    position: "AI Engineer",
    jobPosting: "Machine Learning Engineer",
    recruitmentStage: "Technical Test",
    evaluation: "Excellent",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Bac Tu Liem"
  },
  {
  fullName: "Tran Thi Bich",
  phoneNumber: "0912345678",
  candidateSource: "Website",
  email: "bich.tran@gmail.com",
  recruitmentCampaign: "Dev Hiring 2026",
  position: "Backend Developer",
  jobPosting: "Java Developer",
  recruitmentStage: "Interview",
  evaluation: "Good",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Ba Dinh",
},
{
  fullName: "Le Van Cuong",
  phoneNumber: "0934567890",
  candidateSource: "LinkedIn",
  email: "cuong.le@gmail.com",
  recruitmentCampaign: "Marketing Hiring",
  position: "SEO Specialist",
  jobPosting: "SEO Executive",
  recruitmentStage: "CV Screening",
  evaluation: "Average",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Dong Da",
},
{
  fullName: "Pham Thi Dao",
  phoneNumber: "0978881111",
  candidateSource: "Facebook",
  email: "dao.pham@gmail.com",
  recruitmentCampaign: "Design Hiring",
  position: "UI Designer",
  jobPosting: "UI/UX Designer",
  recruitmentStage: "Offer",
  evaluation: "Excellent",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Hai Ba Trung",
},
{
  fullName: "Hoang Van Duc",
  phoneNumber: "0967772222",
  candidateSource: "Website",
  email: "duc.hoang@gmail.com",
  recruitmentCampaign: "Dev Hiring 2026",
  position: "Frontend Developer",
  jobPosting: "VueJS Developer",
  recruitmentStage: "Interview",
  evaluation: "Good",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Thanh Xuan",
},
{
  fullName: "Nguyen Thi Hanh",
  phoneNumber: "0945556666",
  candidateSource: "LinkedIn",
  email: "hanh.nguyen@gmail.com",
  recruitmentCampaign: "HR Hiring",
  position: "HR Executive",
  jobPosting: "HR Specialist",
  recruitmentStage: "CV Screening",
  evaluation: "Potential",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Long Bien",
},
{
  fullName: "Do Van Hung",
  phoneNumber: "0922223333",
  candidateSource: "Facebook",
  email: "hung.do@gmail.com",
  recruitmentCampaign: "Dev Hiring 2026",
  position: "Backend Developer",
  jobPosting: "Spring Boot Developer",
  recruitmentStage: "Interview",
  evaluation: "Good",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Cau Giay",
},
{
  fullName: "Bui Thi Lan",
  phoneNumber: "0981112222",
  candidateSource: "Website",
  email: "lan.bui@gmail.com",
  recruitmentCampaign: "Design Hiring",
  position: "Graphic Designer",
  jobPosting: "Graphic Designer",
  recruitmentStage: "CV Screening",
  evaluation: "Average",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Tay Ho",
},
{
  fullName: "Dang Van Minh",
  phoneNumber: "0919990000",
  candidateSource: "LinkedIn",
  email: "minh.dang@gmail.com",
  recruitmentCampaign: "Dev Hiring 2026",
  position: "Fullstack Developer",
  jobPosting: "NodeJS Developer",
  recruitmentStage: "Interview",
  evaluation: "Good",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Hoang Mai",
},
{
  fullName: "Vu Thi Nga",
  phoneNumber: "0901230000",
  candidateSource: "Facebook",
  email: "nga.vu@gmail.com",
  recruitmentCampaign: "Marketing Hiring",
  position: "Content Writer",
  jobPosting: "Content Marketing",
  recruitmentStage: "Offer",
  evaluation: "Excellent",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Nam Tu Liem",
},
{
  fullName: "Trinh Van Phu",
  phoneNumber: "0937778888",
  candidateSource: "Website",
  email: "phu.trinh@gmail.com",
  recruitmentCampaign: "Dev Hiring 2026",
  position: "QA Engineer",
  jobPosting: "Tester",
  recruitmentStage: "Interview",
  evaluation: "Potential",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Bac Tu Liem",
},
{
  fullName: "Pham Van Quang",
  phoneNumber: "0940001111",
  candidateSource: "LinkedIn",
  email: "quang.pham@gmail.com",
  recruitmentCampaign: "Dev Hiring 2026",
  position: "Backend Developer",
  jobPosting: "PHP Developer",
  recruitmentStage: "CV Screening",
  evaluation: "Average",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Dong Da",
},
{
  fullName: "Le Thi Thu",
  phoneNumber: "0953334444",
  candidateSource: "Facebook",
  email: "thu.le@gmail.com",
  recruitmentCampaign: "HR Hiring",
  position: "Recruiter",
  jobPosting: "HR Recruiter",
  recruitmentStage: "Interview",
  evaluation: "Good",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Ba Dinh",
},
{
  fullName: "Nguyen Van Tuan",
  phoneNumber: "0974445555",
  candidateSource: "Website",
  email: "tuan.nguyen@gmail.com",
  recruitmentCampaign: "Dev Hiring 2026",
  position: "DevOps Engineer",
  jobPosting: "AWS Engineer",
  recruitmentStage: "Offer",
  evaluation: "Excellent",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Cau Giay",
},
{
  fullName: "Tran Thi Uyen",
  phoneNumber: "0982223333",
  candidateSource: "LinkedIn",
  email: "uyen.tran@gmail.com",
  recruitmentCampaign: "Marketing Hiring",
  position: "Digital Marketer",
  jobPosting: "Digital Marketing",
  recruitmentStage: "Interview",
  evaluation: "Good",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Thanh Xuan",
},
{
  fullName: "Hoang Van Viet",
  phoneNumber: "0909998888",
  candidateSource: "Facebook",
  email: "viet.hoang@gmail.com",
  recruitmentCampaign: "Dev Hiring 2026",
  position: "Frontend Developer",
  jobPosting: "ReactJS Developer",
  recruitmentStage: "CV Screening",
  evaluation: "Potential",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Long Bien",
},
{
  fullName: "Dang Thi Yen",
  phoneNumber: "0911113333",
  candidateSource: "Website",
  email: "yen.dang@gmail.com",
  recruitmentCampaign: "Design Hiring",
  position: "UI Designer",
  jobPosting: "UX Designer",
  recruitmentStage: "Interview",
  evaluation: "Good",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Tay Ho",
},
{
  fullName: "Bui Van Anh",
  phoneNumber: "0924446666",
  candidateSource: "LinkedIn",
  email: "anh.bui@gmail.com",
  recruitmentCampaign: "Dev Hiring 2026",
  position: "Fullstack Developer",
  jobPosting: "MERN Developer",
  recruitmentStage: "Offer",
  evaluation: "Excellent",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Hoang Mai",
},
{
  fullName: "Pham Thi Binh",
  phoneNumber: "0932221111",
  candidateSource: "Facebook",
  email: "binh.pham@gmail.com",
  recruitmentCampaign: "HR Hiring",
  position: "HR Assistant",
  jobPosting: "HR Admin",
  recruitmentStage: "CV Screening",
  evaluation: "Average",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Nam Tu Liem",
},
{
  fullName: "Nguyen Van Chung",
  phoneNumber: "0946667777",
  candidateSource: "Website",
  email: "chung.nguyen@gmail.com",
  recruitmentCampaign: "Dev Hiring 2026",
  position: "Backend Developer",
  jobPosting: "NodeJS Developer",
  recruitmentStage: "Interview",
  evaluation: "Good",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Bac Tu Liem",
},
{
  fullName: "Tran Thi Dung",
  phoneNumber: "0958887777",
  candidateSource: "LinkedIn",
  email: "dung.tran@gmail.com",
  recruitmentCampaign: "Marketing Hiring",
  position: "Content Writer",
  jobPosting: "Content Executive",
  recruitmentStage: "Offer",
  evaluation: "Excellent",
  country: "Vietnam",
  province: "Ha Noi",
  ward: "Hai Ba Trung",
},
];
