const employees = [
  {
    fullName: "Nguyen Van An",
    phoneNumber: "0987654321",
    candidateSource: "Facebook",
    email: "an.nguyen@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "Frontend Developer",
    jobPosting: "ReactJS Developer",
    recruitmentStage: "CV Screening",
    evaluation: "Potential",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Cau Giay",
  },
  {
    fullName: "Tran Thi Bich",
    phoneNumber: "0978123456",
    candidateSource: "LinkedIn",
    email: "bich.tran@gmail.com",
    recruitmentCampaign: "Intern Hiring 2026",
    position: "Backend Intern",
    jobPosting: "Java Spring Boot",
    recruitmentStage: "HR Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Dong Da",
  },
  {
    fullName: "Le Minh Cuong",
    phoneNumber: "0912345678",
    candidateSource: "TopCV",
    email: "cuong.le@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "Fullstack Developer",
    jobPosting: "NodeJS + React",
    recruitmentStage: "Technical Interview",
    evaluation: "Average",
    country: "Vietnam",
    province: "Da Nang",
    ward: "Hai Chau",
  },
  {
    fullName: "Pham Thu Dung",
    phoneNumber: "0909123456",
    candidateSource: "Website",
    email: "dung.pham@gmail.com",
    recruitmentCampaign: "Marketing Hiring",
    position: "Digital Marketing",
    jobPosting: "Marketing Executive",
    recruitmentStage: "CV Screening",
    evaluation: "Average",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Thanh Xuan",
  },
  {
    fullName: "Do Hoang Nam",
    phoneNumber: "0933456789",
    candidateSource: "Referral",
    email: "nam.do@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "Backend Developer",
    jobPosting: "Java Developer",
    recruitmentStage: "Offer",
    evaluation: "Excellent",
    country: "Vietnam",
    province: "Hai Phong",
    ward: "Le Chan",
  },
  {
    fullName: "Nguyen Thi Hoa",
    phoneNumber: "0966111222",
    candidateSource: "Facebook",
    email: "hoa.nguyen@gmail.com",
    recruitmentCampaign: "Intern Hiring 2026",
    position: "Frontend Intern",
    jobPosting: "React Intern",
    recruitmentStage: "HR Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Ba Dinh",
  },
  {
    fullName: "Bui Van Khanh",
    phoneNumber: "0944556677",
    candidateSource: "LinkedIn",
    email: "khanh.bui@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "DevOps Engineer",
    jobPosting: "AWS DevOps",
    recruitmentStage: "Technical Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ho Chi Minh",
    ward: "District 7",
  },
  {
    fullName: "Phan Ngoc Lan",
    phoneNumber: "0922333444",
    candidateSource: "TopCV",
    email: "lan.phan@gmail.com",
    recruitmentCampaign: "HR Hiring",
    position: "HR Executive",
    jobPosting: "HR Generalist",
    recruitmentStage: "HR Interview",
    evaluation: "Average",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Hoan Kiem",
  },
  {
    fullName: "Vu Duc Thanh",
    phoneNumber: "0911222333",
    candidateSource: "Website",
    email: "thanh.vu@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "Backend Developer",
    jobPosting: "Spring Boot Developer",
    recruitmentStage: "CV Screening",
    evaluation: "Potential",
    country: "Vietnam",
    province: "Da Nang",
    ward: "Son Tra",
  },
  {
    fullName: "Trinh Mai Anh",
    phoneNumber: "0988111222",
    candidateSource: "Facebook",
    email: "anh.trinh@gmail.com",
    recruitmentCampaign: "Marketing Hiring",
    position: "Content Marketing",
    jobPosting: "Content Creator",
    recruitmentStage: "Final Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Tay Ho",
  },
  {
    fullName: "Dang Tuan Kiet",
    phoneNumber: "0977111222",
    candidateSource: "LinkedIn",
    email: "kiet.dang@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "Frontend Developer",
    jobPosting: "VueJS Developer",
    recruitmentStage: "Technical Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Ho Chi Minh",
    ward: "District 3",
  },
  {
    fullName: "Hoang Minh Duc",
    phoneNumber: "0967222333",
    candidateSource: "TopCV",
    email: "duc.hoang@gmail.com",
    recruitmentCampaign: "Intern Hiring 2026",
    position: "Backend Intern",
    jobPosting: "NodeJS Intern",
    recruitmentStage: "HR Interview",
    evaluation: "Potential",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Nam Tu Liem",
  },
  {
    fullName: "Nguyen Quoc Huy",
    phoneNumber: "0955333444",
    candidateSource: "Facebook",
    email: "huy.nguyen@gmail.com",
    recruitmentCampaign: "Dev Hiring 2026",
    position: "Fullstack Developer",
    jobPosting: "React + Spring Boot",
    recruitmentStage: "Technical Interview",
    evaluation: "Good",
    country: "Vietnam",
    province: "Da Nang",
    ward: "Thanh Khe",
  },
  {
    fullName: "Le Thi Thao",
    phoneNumber: "0946444555",
    candidateSource: "Website",
    email: "thao.le@gmail.com",
    recruitmentCampaign: "Marketing Hiring",
    position: "SEO Specialist",
    jobPosting: "SEO Executive",
    recruitmentStage: "CV Screening",
    evaluation: "Average",
    country: "Vietnam",
    province: "Ha Noi",
    ward: "Long Bien",
  },
];
